

services:
  unicon-landing:
    container_name: unicon-landing
    build:
      context: .
      dockerfile: deployment/prod.Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_SITE_BASE_URL: ${NEXT_PUBLIC_SITE_BASE_URL}
        NEXT_PUBLIC_APP_BASE_URL: ${NEXT_PUBLIC_APP_BASE_URL}
        NEXT_PUBLIC_GA_MEASUREMENT_ID_PUBLIC: ${NEXT_PUBLIC_GA_MEASUREMENT_ID_PUBLIC}
        NEXT_PUBLIC_YANDEX_VERIFICATION: ${NEXT_PUBLIC_YANDEX_VERIFICATION}
        NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}
    restart: always
    ports:
      - "3000:3000"
    # networks:
    #   - unicon_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   unicon_network:
#     external: true